### ISSUE TITLE
PHP7 deprecated error

### ISSUE THREAD

**Issue by merrill-oakland** [moodleou/moodle-tool_editrolesbycap#4]
[This line](https://github.com/moodleou/moodle-tool_editrolesbycap/blob/master/capabilityformfield.php#L36) has a PHP 4 constructor and no PHP 5 constructor, so it emmits a E_DEPRECATED.

**Comment by timhunt** [comment]
Thanks for the pull request, but in the end we fixed this ourselves. Closing.
