### ISSUE TITLE
Capabilities for mod_h5pactivity can't be edited

### ISSUE THREAD

**Issue by abias** [moodleou/moodle-tool_editrolesbycap#9]
Hi Tim,

I noticed on our Moodle 3.9 instance that I can't edit the capabilities of mod_h5pactivity with this really helpful plugin.

Steps to reproduce:
* Go to Site administration -> Users -> Permissions -> Edit roles by capability
* Search for mod/h5pactivity in the list of capabilities
* Try to filter for the term "h5pactivity"

Expected result:
* The capabilities of mod_h5pactivity are found and can be editied.

Actual result:
* The capabilities are not listed in the list of capabilities
* Filtering for the "h5pactivity" term does not give any results.

Interpretation:
Other H5P-related capabilities like moodle/h5p:deploy can be found. So it's no fundamental problem with the "h5p" term.
But I remember that there had to be a policy / library chance in Moodle core before Moodle allowed an activity to use a number in its Frankenstyle name and before mod_h5pactivity could be labeled with this name. For the same reason, the original H5P activity from Joubel is called mod_hvp.
Maybe tool_editrolesbycap has to be adapted to this policy change as well?

Thanks,
Alex

**Comment by timhunt** [comment]
![image](https://user-images.githubusercontent.com/138653/100870391-781f7b80-3496-11eb-8834-86e352afcf9f.png)

![image](https://user-images.githubusercontent.com/138653/100870480-938a8680-3496-11eb-95dd-c7a4e04a8db2.png)

**Comment by abias** [comment]
Oh, that's interesting!

So I had a look at get_capabitity_optgroups() in capabilityformfield.php.

And I saw that in line https://github.com/moodleou/moodle-tool_editrolesbycap/blob/master/capabilityformfield.php#L58, the mod/h5pactivity capabilities are there in the $capabilities array indeed, but in line https://github.com/moodleou/moodle-tool_editrolesbycap/blob/master/capabilityformfield.php#L89, the $optgroups array does not contain them anymore.

If I add this small patch to the plugin:
`[abias@moodle-test1 moodle_ng]$ git diff
diff --git a/admin/tool/editrolesbycap/capabilityformfield.php b/admin/tool/editrolesbycap/capabilityformfield.php
index bd34d51..1851cb5 100644
--- a/admin/tool/editrolesbycap/capabilityformfield.php
+++ b/admin/tool/editrolesbycap/capabilityformfield.php
@@ -77,8 +77,12 @@ class MoodleQuickForm_capability extends MoodleQuickForm_selectgroups {
             $a = new stdClass();
             $a->name = get_capability_string($capability->name);
             $a->capabilityname = $capability->name;
+
             $currentgroup[$capability->name] = get_string('capabilityandname',
                     'tool_editrolesbycap', $a);
+            if (strpos($capability->name, 'h5pa') !== false) {
+                break;
+            }
         }
 
         // Remeber to add the currently open optgroup.`
then at least the mod/h5pactivity:addinstance capability is listed in the capability select widget.
However, if I remove the patch again, none of the mod/h5pactivity:addinstance capabilities are there anymore in the capability select widget.

They must get lost somewhere within https://github.com/moodleou/moodle-tool_editrolesbycap/blob/master/capabilityformfield.php#L60-L87, but I am running out of time now to investigate that in more depth....

**Comment by timhunt** [comment]
I see what is going on. Where it groups the capabilities, it assumes that all the capabiltiies for one group come consecutively. If it has to go back to a group it previously started, then it starts again with a blank array.

Now I see that, I will fix it.

**Comment by abias** [comment]
That's great!
Thank you for the investigation and this fix, Tim!
